### ISSUE TITLE
 Scraping yerine API kullanımı 

### ISSUE THREAD

**Issue by Noonlord** [egmnklc/deprem-bot#1]
Merhaba. Scraping yapmak yerine direkt API'mizden çekebilirsiniz. https://deprem.noonlordhost.com/

**Comment by egmnklc** [comment]
Çok teşekkür ederim, projeyi güncelliyorum şimdi.

**Comment by egmnklc** [comment]
Bu discord sunucusunda IT Destek ekibi kurulmuş durumda. Dilerseniz dahil olup size uygun süreçlere dahil olabilirsiniz: https://discord.gg/itdepremyardim

**Comment by egmnklc** [comment]
API'inizi nasıl yazdığınızı paylaşabilir misiniz, bildiklerimle yardımcı
olmak için böyle bir proje yaptım. Sizin yaptığınız işi de öğrenmek isterim.
